
                      rsreset
LevelId:              rs.w       1
LevelPtr:             rs.l       1
GameMapCeiling:       rs.b       WALL_PAPER_WIDTH
GameMap:              rs.b       WALL_PAPER_SIZE
WallpaperCheat:       rs.b       WALL_PAPER_WIDTH
WallpaperWork:        rs.b       WALL_PAPER_SIZE
RandomSeed:           rs.l       1
WallpaperLadders:     rs.b       WALL_PAPER_SIZE
WallpaperShadows:     rs.b       WALL_PAPER_SIZE
TilesetPtr:           rs.l       1
AssetSet:             rs.w       1
MoveId:               rs.w       1
PlayerPtrs:           rs.l       2
Millie:               rs.b       Player_Sizeof
Molly:                rs.b       Player_Sizeof
GameStatus:           rs.w       1
ScreenPtrs:           rs.l       2
SpritePtrs:           rs.l       8
ActorCount:           rs.w       1
Actors:               rs.b       Actor_Sizeof*MAX_ACTORS
TickCounter:          rs.w       1
ControlsTrigger:      rs.b       1 
ControlsHold:         rs.b       1 
PlayerMoved:          rs.w       1
PlayerCount:          rs.w       1
LevelComplete:        rs.w       1
ActionStatus:         rs.w       1
PushedActor:          rs.l       1
ActionCounter:        rs.w       1
TitleStars:           rs.l       TITLE_STAR_COUNT
FallenActors:         rs.l       MAP_SIZE
FallenActorsCount:    rs.w       1
ClearMasks:           rs.l       TILE_WIDTH
ActorSlotPtr:         rs.l       1 
ActorList:            rs.l       MAP_SIZE
Variables_sizeof:     rs.w       0
